<?xml version="1.0" encoding="utf-8"?><Database Name="LibraryManagementSystem" Class="DB_MemberTableDataContext" xmlns="http://schemas.microsoft.com/linqtosql/dbml/2007">
  <Connection Mode="AppSettings" ConnectionString="Data Source=DESKTOP-JJMIDS9\MSSQL;Initial Catalog=LibraryManagementSystem;Integrated Security=True" SettingsObjectName="wpfThreeView.Properties.Settings" SettingsPropertyName="LibraryManagementSystemConnectionString" Provider="System.Data.SqlClient" />
  <Table Name="dbo.Member" Member="Table_Members">
    <Type Name="Table_Member">
      <Column Name="Member_ID" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="Member_ID_Code" Type="System.String" DbType="VarChar(6)" IsDbGenerated="true" CanBeNull="true" UpdateCheck="Never" />
      <Column Name="First_Name" Type="System.String" DbType="VarChar(20) NOT NULL" CanBeNull="false" />
      <Column Name="Last_Name" Type="System.String" DbType="VarChar(20) NOT NULL" CanBeNull="false" />
      <Column Name="Age" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="Gender" Type="System.Char" DbType="Char(1)" CanBeNull="true" />
      <Column Name="Type" Type="System.String" DbType="VarChar(20) NOT NULL" CanBeNull="false" />
      <Column Name="E_Mail" Type="System.String" DbType="VarChar(30)" CanBeNull="true" />
      <Column Name="No_Of_Book_Borrowed" Type="System.Int32" DbType="Int" CanBeNull="true" />
    </Type>
  </Table>
</Database>