#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace wpfThreeView.DBTables
{
	using System.Data.Linq;
	using System.Data.Linq.Mapping;
	using System.Data;
	using System.Collections.Generic;
	using System.Reflection;
	using System.Linq;
	using System.Linq.Expressions;
	using System.ComponentModel;
	using System;
	
	
	[global::System.Data.Linq.Mapping.DatabaseAttribute(Name="LibraryManagementSystem")]
	public partial class DBBookTableDataContext : System.Data.Linq.DataContext
	{
		
		private static System.Data.Linq.Mapping.MappingSource mappingSource = new AttributeMappingSource();
		
    #region Extensibility Method Definitions
    partial void OnCreated();
    partial void InsertTable_Book(Table_Book instance);
    partial void UpdateTable_Book(Table_Book instance);
    partial void DeleteTable_Book(Table_Book instance);
    #endregion
		
		public DBBookTableDataContext() : 
				base(global::wpfThreeView.Properties.Settings.Default.LibraryManagementSystemConnectionString, mappingSource)
		{
			OnCreated();
		}
		
		public DBBookTableDataContext(string connection) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public DBBookTableDataContext(System.Data.IDbConnection connection) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public DBBookTableDataContext(string connection, System.Data.Linq.Mapping.MappingSource mappingSource) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public DBBookTableDataContext(System.Data.IDbConnection connection, System.Data.Linq.Mapping.MappingSource mappingSource) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public System.Data.Linq.Table<Table_Book> Table_Books
		{
			get
			{
				return this.GetTable<Table_Book>();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.Book")]
	public partial class Table_Book : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _Book_ID;
		
		private string _Book_ID_Code;
		
		private string _Title;
		
		private string _Author;
		
		private System.Nullable<int> _No_Of_Coppies;
		
		private System.Nullable<int> _Avilability;
		
		private System.Nullable<int> _Rack_No;
		
		private string _ISBN;
		
		private string _Publisher;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnBook_IDChanging(int value);
    partial void OnBook_IDChanged();
    partial void OnBook_ID_CodeChanging(string value);
    partial void OnBook_ID_CodeChanged();
    partial void OnTitleChanging(string value);
    partial void OnTitleChanged();
    partial void OnAuthorChanging(string value);
    partial void OnAuthorChanged();
    partial void OnNo_Of_CoppiesChanging(System.Nullable<int> value);
    partial void OnNo_Of_CoppiesChanged();
    partial void OnAvilabilityChanging(System.Nullable<int> value);
    partial void OnAvilabilityChanged();
    partial void OnRack_NoChanging(System.Nullable<int> value);
    partial void OnRack_NoChanged();
    partial void OnISBNChanging(string value);
    partial void OnISBNChanged();
    partial void OnPublisherChanging(string value);
    partial void OnPublisherChanged();
    #endregion
		
		public Table_Book()
		{
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Book_ID", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public int Book_ID
		{
			get
			{
				return this._Book_ID;
			}
			set
			{
				if ((this._Book_ID != value))
				{
					this.OnBook_IDChanging(value);
					this.SendPropertyChanging();
					this._Book_ID = value;
					this.SendPropertyChanged("Book_ID");
					this.OnBook_IDChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Book_ID_Code", AutoSync=AutoSync.Always, DbType="VarChar(7)", IsDbGenerated=true, UpdateCheck=UpdateCheck.Never)]
		public string Book_ID_Code
		{
			get
			{
				return this._Book_ID_Code;
			}
			set
			{
				if ((this._Book_ID_Code != value))
				{
					this.OnBook_ID_CodeChanging(value);
					this.SendPropertyChanging();
					this._Book_ID_Code = value;
					this.SendPropertyChanged("Book_ID_Code");
					this.OnBook_ID_CodeChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Title", DbType="VarChar(50)")]
		public string Title
		{
			get
			{
				return this._Title;
			}
			set
			{
				if ((this._Title != value))
				{
					this.OnTitleChanging(value);
					this.SendPropertyChanging();
					this._Title = value;
					this.SendPropertyChanged("Title");
					this.OnTitleChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Author", DbType="VarChar(50)")]
		public string Author
		{
			get
			{
				return this._Author;
			}
			set
			{
				if ((this._Author != value))
				{
					this.OnAuthorChanging(value);
					this.SendPropertyChanging();
					this._Author = value;
					this.SendPropertyChanged("Author");
					this.OnAuthorChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_No_Of_Coppies", DbType="Int")]
		public System.Nullable<int> No_Of_Coppies
		{
			get
			{
				return this._No_Of_Coppies;
			}
			set
			{
				if ((this._No_Of_Coppies != value))
				{
					this.OnNo_Of_CoppiesChanging(value);
					this.SendPropertyChanging();
					this._No_Of_Coppies = value;
					this.SendPropertyChanged("No_Of_Coppies");
					this.OnNo_Of_CoppiesChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Avilability", DbType="Int")]
		public System.Nullable<int> Avilability
		{
			get
			{
				return this._Avilability;
			}
			set
			{
				if ((this._Avilability != value))
				{
					this.OnAvilabilityChanging(value);
					this.SendPropertyChanging();
					this._Avilability = value;
					this.SendPropertyChanged("Avilability");
					this.OnAvilabilityChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Rack_No", DbType="Int")]
		public System.Nullable<int> Rack_No
		{
			get
			{
				return this._Rack_No;
			}
			set
			{
				if ((this._Rack_No != value))
				{
					this.OnRack_NoChanging(value);
					this.SendPropertyChanging();
					this._Rack_No = value;
					this.SendPropertyChanged("Rack_No");
					this.OnRack_NoChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ISBN", DbType="VarChar(13) NOT NULL", CanBeNull=false)]
		public string ISBN
		{
			get
			{
				return this._ISBN;
			}
			set
			{
				if ((this._ISBN != value))
				{
					this.OnISBNChanging(value);
					this.SendPropertyChanging();
					this._ISBN = value;
					this.SendPropertyChanged("ISBN");
					this.OnISBNChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Publisher", DbType="VarChar(50)")]
		public string Publisher
		{
			get
			{
				return this._Publisher;
			}
			set
			{
				if ((this._Publisher != value))
				{
					this.OnPublisherChanging(value);
					this.SendPropertyChanging();
					this._Publisher = value;
					this.SendPropertyChanged("Publisher");
					this.OnPublisherChanged();
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
}
#pragma warning restore 1591
