#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace wpfThreeView.DBTables
{
	using System.Data.Linq;
	using System.Data.Linq.Mapping;
	using System.Data;
	using System.Collections.Generic;
	using System.Reflection;
	using System.Linq;
	using System.Linq.Expressions;
	using System.ComponentModel;
	using System;
	
	
	[global::System.Data.Linq.Mapping.DatabaseAttribute(Name="LibraryManagementSystem")]
	public partial class DBCatalogueTableDataContext : System.Data.Linq.DataContext
	{
		
		private static System.Data.Linq.Mapping.MappingSource mappingSource = new AttributeMappingSource();
		
    #region Extensibility Method Definitions
    partial void OnCreated();
    partial void InsertTable_Catalogue(Table_Catalogue instance);
    partial void UpdateTable_Catalogue(Table_Catalogue instance);
    partial void DeleteTable_Catalogue(Table_Catalogue instance);
    #endregion
		
		public DBCatalogueTableDataContext() : 
				base(global::wpfThreeView.Properties.Settings.Default.LibraryManagementSystemConnectionString, mappingSource)
		{
			OnCreated();
		}
		
		public DBCatalogueTableDataContext(string connection) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public DBCatalogueTableDataContext(System.Data.IDbConnection connection) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public DBCatalogueTableDataContext(string connection, System.Data.Linq.Mapping.MappingSource mappingSource) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public DBCatalogueTableDataContext(System.Data.IDbConnection connection, System.Data.Linq.Mapping.MappingSource mappingSource) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public System.Data.Linq.Table<Table_Catalogue> Table_Catalogues
		{
			get
			{
				return this.GetTable<Table_Catalogue>();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.Catalogue")]
	public partial class Table_Catalogue : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private string _BID;
		
		private string _Book_Name;
		
		private string _Author_Name;
		
		private System.Nullable<int> _ISBN;
		
		private System.Nullable<int> _No_Of_Copies;
		
		private System.Nullable<int> _Avilable_Copies;
		
		private System.Nullable<int> _Rack_No;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnBIDChanging(string value);
    partial void OnBIDChanged();
    partial void OnBook_NameChanging(string value);
    partial void OnBook_NameChanged();
    partial void OnAuthor_NameChanging(string value);
    partial void OnAuthor_NameChanged();
    partial void OnISBNChanging(System.Nullable<int> value);
    partial void OnISBNChanged();
    partial void OnNo_Of_CopiesChanging(System.Nullable<int> value);
    partial void OnNo_Of_CopiesChanged();
    partial void OnAvilable_CopiesChanging(System.Nullable<int> value);
    partial void OnAvilable_CopiesChanged();
    partial void OnRack_NoChanging(System.Nullable<int> value);
    partial void OnRack_NoChanged();
    #endregion
		
		public Table_Catalogue()
		{
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_BID", DbType="Char(6) NOT NULL", CanBeNull=false, IsPrimaryKey=true)]
		public string BID
		{
			get
			{
				return this._BID;
			}
			set
			{
				if ((this._BID != value))
				{
					this.OnBIDChanging(value);
					this.SendPropertyChanging();
					this._BID = value;
					this.SendPropertyChanged("BID");
					this.OnBIDChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Book_Name", DbType="VarChar(1)")]
		public string Book_Name
		{
			get
			{
				return this._Book_Name;
			}
			set
			{
				if ((this._Book_Name != value))
				{
					this.OnBook_NameChanging(value);
					this.SendPropertyChanging();
					this._Book_Name = value;
					this.SendPropertyChanged("Book_Name");
					this.OnBook_NameChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Author_Name", DbType="VarChar(1)")]
		public string Author_Name
		{
			get
			{
				return this._Author_Name;
			}
			set
			{
				if ((this._Author_Name != value))
				{
					this.OnAuthor_NameChanging(value);
					this.SendPropertyChanging();
					this._Author_Name = value;
					this.SendPropertyChanged("Author_Name");
					this.OnAuthor_NameChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ISBN", DbType="Int")]
		public System.Nullable<int> ISBN
		{
			get
			{
				return this._ISBN;
			}
			set
			{
				if ((this._ISBN != value))
				{
					this.OnISBNChanging(value);
					this.SendPropertyChanging();
					this._ISBN = value;
					this.SendPropertyChanged("ISBN");
					this.OnISBNChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_No_Of_Copies", DbType="Int")]
		public System.Nullable<int> No_Of_Copies
		{
			get
			{
				return this._No_Of_Copies;
			}
			set
			{
				if ((this._No_Of_Copies != value))
				{
					this.OnNo_Of_CopiesChanging(value);
					this.SendPropertyChanging();
					this._No_Of_Copies = value;
					this.SendPropertyChanged("No_Of_Copies");
					this.OnNo_Of_CopiesChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Avilable_Copies", DbType="Int")]
		public System.Nullable<int> Avilable_Copies
		{
			get
			{
				return this._Avilable_Copies;
			}
			set
			{
				if ((this._Avilable_Copies != value))
				{
					this.OnAvilable_CopiesChanging(value);
					this.SendPropertyChanging();
					this._Avilable_Copies = value;
					this.SendPropertyChanged("Avilable_Copies");
					this.OnAvilable_CopiesChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Rack_No", DbType="Int")]
		public System.Nullable<int> Rack_No
		{
			get
			{
				return this._Rack_No;
			}
			set
			{
				if ((this._Rack_No != value))
				{
					this.OnRack_NoChanging(value);
					this.SendPropertyChanging();
					this._Rack_No = value;
					this.SendPropertyChanged("Rack_No");
					this.OnRack_NoChanged();
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
}
#pragma warning restore 1591
